### ISSUE TITLE
特性能不能合并到一起，套娃一下，多个特性有点麻烦ExcelColumnName、ExcelIgnore、ExcelFormat

### ISSUE THREAD

**Issue by MonsterUncle** [MiniExcel/MiniExcel#353]
[ExcelColumnName("修改时间")]
[ExcelFormat("yyyy-MM-dd HH:mm:ss")]
[ExcelIgnore]
改成这样可以不[
](https://images.gitee.com/uploads/images/2022/0328/173254_6f40f55e_7353672.png)

**Comment by MonsterUncle** [comment]
一个特性多个参数，这几个特性继承套娃一下

**Comment by shps951023** [comment]
感谢 @Weilence 帮忙实现，下个版本会更新
