### ISSUE TITLE
dotnet 6 support

### ISSUE THREAD

**Issue by nutthawutkongsopa** [MiniExcel/MiniExcel#382]
### Excel Type

- [ ] XLSX
- [ ] XLSM
- [ ] CSV
- [ ] OTHER

### Upload Excel File

Please attach your issue file by dragging or droppng, selecting or pasting them.

e.g : [https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx](https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx)

### Description
Kindly upgrade for support dotnet 6.
thank you

**Comment by shps951023** [comment]
MiniExcel support dotnet 6 now, is there any problems?

**Comment by nutthawutkongsopa** [comment]
It's working thanks.
